sudo: required
language: go
go_import_path: github.com/XinFinOrg/XDPoSChain
branches:
  only:
  - master
  - dev-upgrade

env:
  global:
    - GOPROXY=https://proxy.golang.org
    - GO111MODULE=on
    # Terraform env
    - tf_version=1.3.0
    # Setting terraform init CLI options - https://www.terraform.io/docs/commands/init.html
    - tf_init_cli_options=" -input=false"
    # Set terraform validation CLI options - https://www.terraform.io/docs/commands/validate.html
    - tf_validation_cli_options=""
    # Set terraform plan CLI options - https://www.terraform.io/docs/commands/plan.html
    - tf_plan_cli_options=" -lock=false -input=false"
    # Set terraform apply CLI options - https://www.terraform.io/docs/commands/apply.html
    - tf_apply_cli_options=" -auto-approve -input=false"


jobs:
  include:
  # TODO: temporary turn off linting to help fix all the tests. We will turn it back on once the branch is stable
  # - stage: Lint
  #   sudo: false
  #   go: '1.14.x'
  #   git:
  #     submodules: false
  #     script:
  #       - go run build/ci.go lint

  - stage: (Devnet) Build, and push images
    if: branch = dev-upgrade-hot-fix AND type = push AND tag IS blank
    services:
      - docker
    install: skip
    before_script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker --version  # document the version travis is using
      - docker build -t xdc-devnet -f cicd/devnet/Dockerfile .
    script:
      - docker tag xdc-devnet:latest xinfinorg/devnet:latest # Always push to the latest
      - docker push xinfinorg/devnet:latest
